// CONTADOR
export const INCREMENT = "INCREMENT";
export const DECREMENT = "DECREMENT";
export const INCREMENT2 = "INCREMENT2";
export const DECREMENT2 = "DECREMENT2";
export const DECREMENTRANDOM = "DECREMENTRANDOM";
export const INCREMENTRANDOM = "INCREMENTRANDOM";
export const RESET = "RESET";

// CART

export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_ONE_FROM_CART = "REMOVE_ONE_FROM_CART"
export const REMOVE_ALL_FROM_CART = "REMOVE_ALL_FROM_CART";
export const CLEAR_CART = "CLEAR_CART";